---
abstract: 'Catalyst model for the Akismet anti-spam protocol'
author:
  - 'Marcus Ramberg <mramberg@cpan.org'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-Akismet
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Runtime: 5.70
  Class::C3: 0
  Net::Akismet::Protocol: 0
version: 0.02
